env:
  global:
    - CC_TEST_REPORTER_ID=91c0d3ce1f2a80dffcc0fd3eca9efd87b24941c2cc8040d4e8be60316ef8197d
language: node_js
node_js:
  - "stable"
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_script:
  - psql -c 'create database ieuaevuf;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build